// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokAsset, StoryblokRichtext } from '../storyblok.d.ts';
export interface Author {
  avatar?: StoryblokAsset;
  name?: string;
  component: "Author";
  _uid: string;
  [k: string]: unknown;
}

export interface Feature {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface Grid {
  columns?: (Author | Feature | Grid | Page | Post | Teaser)[];
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (Author | Feature | Grid | Page | Post | Teaser)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Post {
  title: string;
  excerpt?: string;
  author?: ISbStoryData<Author> | string;
  mainImage?: StoryblokAsset;
  body: StoryblokRichtext;
  component: "post";
  _uid: string;
  [k: string]: unknown;
}

export interface Teaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = Author | Page | Post;
